#!/bin/bash
set -e
mkdir output
yggconfig
python -c "import yggdrasil"
ygginfo --verbose
echo $CONDA_PREFIX
yggcompile c cpp fortran
# python -m yggdrasil info
# python -m yggdrasil compile-deps c cpp fortran
