#!/bin/bash
set -ex
# yggconfig
# python -c "import yggdrasil"
# ygginfo
# yggcompile
# python -m yggdrasil info
# python -m yggdrasil compile-deps c cpp fortran
yggconfig
python -c "from yggdrasil import tools"
python -c "from yggdrasil.runner import run"
exec "$@"
